name: Build RustDesk iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add aarch64-apple-ios

      - name: Install FFmpeg and pkg-config
        run: |
          brew install ffmpeg pkg-config
          # 验证 FFmpeg 和 pkg-config
          ffmpeg -version
          pkg-config --modversion libavcodec
          # 设置 PKG_CONFIG_PATH
          export PKG_CONFIG_PATH="/usr/local/Cellar/ffmpeg/$(brew list --versions ffmpeg | head -n1 | cut -d' ' -f2)/lib/pkgconfig:$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: |
          cd flutter
          flutter pub get

      - name: Build Rust library
        run: |
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib
        env:
          RUST_BACKTRACE: full # 获取完整回溯

      - name: Build iOS IPA
        run: |
          cd flutter
          flutter clean
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-ios-ipa
          path: flutter/build/ios/ipa/*.ipa
          retention-days: 7
