name: Build RustDesk iOS IPA

on:
  workflow_dispatch: # 手动触发构建
  push:
    branches:
      - master # 或者你的主分支名称

jobs:
  build-ios:
    runs-on: macos-latest # 使用 macOS 运行器
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # 拉取子模块

      # 安装 Rust
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add aarch64-apple-ios

      # 安装 Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # 使用最新稳定版 Flutter
          channel: 'stable'

      # 获取 Flutter 依赖
      - name: Get Flutter dependencies
        run: |
          cd flutter
          flutter pub get

      # 构建 RustDesk 的 Rust 库
      - name: Build Rust library
        run: |
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib

      # 构建未签名的 IPA
      - name: Build IPA
        run: |
          cd flutter
          flutter build ipa --release --no-codesign

      # 上传 IPA 作为构建产物
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-ios-ipa
          path: flutter/build/ios/ipa/*.ipa
          retention-days: 7 # 保留 7 天
