name: Build RustDesk iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate-bridge:
    uses: rustdesk/rustdesk/.github/workflows/bridge.yml@master # 生成桥接代码

  build-ios:
    runs-on: macos-13
    needs: generate-bridge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.75
          targets: aarch64-apple-ios
          components: rustfmt

      - name: Install dependencies
        run: |
          brew install nasm yasm pkg-config

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - name: Patch Flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 6f29f12e82a8293156836ad81cc9bf5af41fe836 # 官方版本
          doNotCache: false

      - name: Install vcpkg dependencies
        run: |
          $VCPKG_ROOT/vcpkg install --triplet arm64-ios --x-install-root="$VCPKG_ROOT/installed"
          export VCPKG_ROOT="$VCPKG_ROOT"
          echo "VCPKG_ROOT=$VCPKG_ROOT" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$VCPKG_ROOT/installed/arm64-ios/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          ls -l "$VCPKG_ROOT/installed/arm64-ios/lib/pkgconfig" # 验证目录
          pkg-config --modversion libopus # 验证 Opus

      - name: Restore bridge files
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Get Flutter dependencies
        run: |
          cd flutter
          flutter pub get

      - name: Build Rust library
        run: |
          cargo build --release --target aarch64-apple-ios --lib
        env:
          RUST_BACKTRACE: full

      - name: Build iOS IPA
        run: |
          cd flutter
          flutter clean
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-ios-ipa
          path: flutter/build/ios/ipa/*.ipa
          retention-days: 7

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          tag_name: "v${{ github.sha }}"
          name: "RustDesk iOS Build ${{ github.sha }}"
          draft: false
          prerelease: true
          files: flutter/build/ios/ipa/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
