name: Build RustDesk iOS IPA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-13 # 官方使用 macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.75 # 官方使用 1.75
          targets: aarch64-apple-ios
          components: rustfmt

      - name: Install dependencies
        run: |
          brew install nasm yasm pkg-config ffmpeg
          # 验证 FFmpeg 和 pkg-config
          ffmpeg -version
          pkg-config --modversion libavcodec
          # 设置 PKG_CONFIG_PATH
          export PKG_CONFIG_PATH="/usr/local/Cellar/ffmpeg/$(brew list --versions ffmpeg | head -n1 | cut -d' ' -f2)/lib/pkgconfig:$PKG_CONFIG_PATH"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5 # 官方使用 3.24.5

      - name: Patch Flutter
        run: |
          cd $(dirname $(dirname $(which flutter)))
          git apply ${{ github.workspace }}/.github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Get Flutter dependencies
        run: |
          cd flutter
          flutter pub get

      - name: Build Rust library
        run: |
          cargo build --features flutter,hwcodec --release --target aarch64-apple-ios --lib --verbose
        env:
          RUST_BACKTRACE: full
          CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG: true

      - name: Build iOS IPA
        run: |
          cd flutter
          flutter clean
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-ios-ipa
          path: flutter/build/ios/ipa/*.ipa
          retention-days: 7

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push'
        with:
          tag_name: "v${{ github.sha }}"
          name: "RustDesk iOS Build ${{ github.sha }}"
          draft: false
          prerelease: true
          files: flutter/build/ios/ipa/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
